### ISSUE TITLE
zerotier client needs to be re-generated and use better raml spec

### ISSUE THREAD

**Issue by despiegk** [zero-os/zerotier_client#8]
- there is issue in go-raml
- needs to use newest raml spec which was +- manually created and more dense

**Comment by despiegk** [comment]
see https://github.com/Jumpscale/go-raml/issues/315

need to check

**Comment by despiegk** [comment]
make sure all works well end2end and is properly documented

**Comment by zaibon** [comment]
updated the README (https://github.com/zero-os/zerotier_client/commit/03993da11e69d837a0308a2f41ae7b378692fd82) to be up to date and also check the full generation of the client.
